<a href="https://colab.research.google.com/github/darpan02-cypher/Knowledge-Data-and-Discovery/blob/main/WordAssociationMining.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install -U git+https://github.com/stephenhky/PyShortTextCategorization

  Cloning https://github.com/stephenhky/PyShortTextCategorization to /tmp/pip-req-build-y0mmssw5
  Running command git clone --filter=blob:none --quiet https://github.com/stephenhky/PyShortTextCategorization /tmp/pip-req-build-y0mmssw5
  Resolved https://github.com/stephenhky/PyShortTextCategorization to commit ef2de02cc5d8115126efa99672b8cf69e506b47d
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done


In [2]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [3]:
!pip install -U scipy==1.12.* numpy==1.25.*

  Using cached scipy-1.12.0-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (60 kB)
  Using cached numpy-1.25.2.tar.gz (10.8 MB)
  Installing build dependencies ... done
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  Getting requirements to build wheel ... error
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.


In [4]:
from google.colab import drive
drive.mount('/content/drive', force_remount=True)

Mounted at /content/drive


In [5]:
# %cd /content/drive/My Drive/ColabData
%cd /content/drive/MyDrive/KDD


/content/drive/MyDrive/KDD


In [6]:
from nltk.corpus import PlaintextCorpusReader
corpus_root = 'HealthNews' # Folder Name
filelists = PlaintextCorpusReader(corpus_root, '.*', encoding='latin-1')  # wildcard is read all files in the folder

In [7]:
!pip install -U shorttext nltk --force-reinstall

  Using cached shorttext-3.0.0-py3-none-any.whl.metadata (10 kB)
  Using cached nltk-3.9.1-py3-none-any.whl.metadata (2.9 kB)
  Using cached numpy-2.3.3-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (62 kB)
  Using cached scipy-1.16.2-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (62 kB)
  Using cached joblib-1.5.2-py3-none-any.whl.metadata (5.6 kB)
  Using cached scikit_learn-1.7.2-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (11 kB)
  Using cached tensorflow-2.20.0-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (4.5 kB)
  Using cached keras-3.11.3-py3-none-any.whl.metadata (5.9 kB)
  Using cached gensim-4.3.3-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (8.1 kB)
  Using cached pandas-2.3.2-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (91 kB)
  Using cached snowballstemmer-3.0.1-py3-none-any.whl.metadata (7.9 kB)
  Using cached numba-0.62.0-cp312-cp312

In [8]:
!pip install -U shorttext==3.0.0 scipy==1.12.0 numpy==1.25.2 --force-reinstall

  Using cached shorttext-3.0.0-py3-none-any.whl.metadata (10 kB)
  Using cached scipy-1.12.0-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (60 kB)
  Using cached numpy-1.25.2.tar.gz (10.8 MB)
  Installing build dependencies ... done
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  Getting requirements to build wheel ... error
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.


In [9]:
from nltk.corpus import PlaintextCorpusReader
corpus_root = 'HealthNews' # Folder Name
filelists = PlaintextCorpusReader(corpus_root, '.*',encoding='latin-1')  # wildcard is read all files in the folder
filelists.fileids()  # Get the filenames

['.DS_Store',
 'Dentistry00500.txt',
 'Dentistry00501.txt',
 'Dentistry00502.txt',
 'Dentistry00503.txt',
 'Dentistry00504.txt',
 'Dentistry00505.txt',
 'Dentistry00506.txt',
 'Dentistry00507.txt',
 'Dentistry00508.txt',
 'Dentistry00509.txt',
 'Dentistry00510.txt',
 'Dentistry00511.txt',
 'Dentistry00512.txt',
 'Dentistry00513.txt',
 'Dentistry00514.txt',
 'Dentistry00515.txt',
 'Dentistry00516.txt',
 'Dentistry00517.txt',
 'Dentistry00518.txt',
 'Dentistry00519.txt',
 'Dentistry00520.txt',
 'Dentistry00521.txt',
 'Dentistry00522.txt',
 'Dentistry00523.txt',
 'Dentistry00524.txt',
 'Dentistry00525.txt',
 'Dentistry00526.txt',
 'Dentistry00527.txt',
 'Dentistry00528.txt',
 'Dentistry00529.txt',
 'Dentistry00530.txt',
 'Dentistry00531.txt',
 'Dentistry00532.txt',
 'Dentistry00533.txt',
 'Dentistry00534.txt',
 'Dentistry00535.txt',
 'Dentistry00536.txt',
 'Dentistry00537.txt',
 'Dentistry00538.txt',
 'Dentistry00539.txt',
 'Dentistry00540.txt',
 'Dentistry00541.txt',
 'Dentistry00542.txt

In [10]:
#create a list of news articles
news = []
for file in filelists.fileids():
    news.append(filelists.raw(file))

In [11]:
news[25]

'New type of cell movement discovered\n <p>For decades, researchers have used petri dishes to study cell movement. These classic tissue culture tools, however, only permit two-dimensional movement, very different from the three-dimensional movements that cells make in a human body.</p><div class="photobox_right" style=\'max-width:349px;\' ><img src="http://www.medicalnewstoday.com/images/articles/281/281729/cell-moving-through-a-3-d-matrix.jpg" alt="Cell Moving through a 3-D Matrix"><br><em>Penn and NIH researchers measured the internal pressure of individual fibroblast cells (in orange) moving through a three-dimensional matrix (in blue). They found that, in this environment, the cells\' nuclei operate like an engine\'s piston to push the cell forward.<br>Credit: University of Pennsylvania/NIDCR</em></div><p>In a new study from the University of Pennsylvania and National Institute of Dental and Craniofacial Research, scientists used an innovative technique to study how cells move in a

In [12]:
# import the shorttext library for text preprocessing
#standard_text_preprocessor_1 under shorttext.utils provides a standard way of text preprocessing, including the following steps:

   #1. removing special characters,
   #2. removing numerals,
   #3. converting all alphabets to lower cases,
   #4. removing stop words, and
   #5. stemming the words (using Porter stemmer).

from shorttext.utils import standard_text_preprocessor_1, DocumentTermMatrix
preprocessor = standard_text_preprocessor_1()
corpus = [preprocessor(article).split(' ') for article in news]

In [13]:
corpus[25]

['new',
 'type',
 'cell',
 'movement',
 'discovered\n',
 'pfor',
 'decad',
 'research',
 'use',
 'petri',
 'dish',
 'studi',
 'cell',
 'movement',
 'classic',
 'tissu',
 'cultur',
 'tool',
 'howev',
 'permit',
 'twodimension',
 'movement',
 'differ',
 'threedimension',
 'movement',
 'cell',
 'make',
 'human',
 'bodypdiv',
 'classphotobox_right',
 'stylemaxwidthpx',
 'img',
 'srchttpwwwmedicalnewstodaycomimagesarticlescellmovingthroughadmatrixjpg',
 'altcel',
 'move',
 'matrixbrempenn',
 'nih',
 'research',
 'measur',
 'intern',
 'pressur',
 'individu',
 'fibroblast',
 'cell',
 'orang',
 'move',
 'threedimension',
 'matrix',
 'blue',
 'found',
 'environ',
 'cell',
 'nuclei',
 'oper',
 'like',
 'engin',
 'piston',
 'push',
 'cell',
 'forwardbrcredit',
 'universiti',
 'pennsylvanianidcremdivpin',
 'new',
 'studi',
 'universiti',
 'pennsylvania',
 'nation',
 'institut',
 'dental',
 'craniofaci',
 'research',
 'scientist',
 'use',
 'innov',
 'techniqu',
 'studi',
 'cell',
 'move',
 'threedi

In [14]:
#convert the corpus of news to a document term matrix (dtm), where each row represents a document, each column represents the number of occurence for a word

dtm = DocumentTermMatrix(corpus, docids = filelists.fileids())

In [15]:
#check number of occurence of the word "associ" in each document
dtm.get_token_occurences('associ')

{'Dentistry00500.txt': 5.0,
 'Dentistry00502.txt': 2.0,
 'Dentistry00503.txt': 1.0,
 'Dentistry00505.txt': 1.0,
 'Dentistry00506.txt': 1.0,
 'Dentistry00512.txt': 2.0,
 'Dentistry00514.txt': 8.0,
 'Dentistry00515.txt': 4.0,
 'Dentistry00516.txt': 1.0,
 'Dentistry00518.txt': 2.0,
 'Dentistry00521.txt': 1.0,
 'Dentistry00523.txt': 7.0,
 'Dentistry00524.txt': 1.0,
 'Dentistry00525.txt': 2.0,
 'Dentistry00526.txt': 1.0,
 'Dentistry00528.txt': 3.0,
 'Dentistry00529.txt': 1.0,
 'Dentistry00530.txt': 8.0,
 'Dentistry00533.txt': 2.0,
 'Dentistry00534.txt': 1.0,
 'Dentistry00535.txt': 1.0,
 'Dentistry00536.txt': 2.0,
 'Dentistry00537.txt': 3.0,
 'Dentistry00538.txt': 2.0,
 'Dentistry00541.txt': 3.0,
 'Dentistry00542.txt': 1.0,
 'Dentistry00544.txt': 1.0,
 'Dentistry00548.txt': 4.0,
 'Dentistry00549.txt': 2.0,
 'Dentistry00550.txt': 2.0,
 'Dentistry00552.txt': 3.0,
 'Dentistry00553.txt': 2.0,
 'Dentistry00554.txt': 1.0,
 'Dentistry00555.txt': 1.0,
 'Dentistry00556.txt': 3.0,
 'Dentistry00557.txt

In [16]:
type(dtm.get_token_occurences('associ'))

dict

In [17]:
# define a function to calculate entropy given a distribution
import numpy as np
import math

def entropy(p):
    if sum(p) == 0:
        return 0

    p = p/sum(p)

    H = -sum(p*np.log2(p))

    return H

In [18]:
entropy(np.array( [12,45]))

0.7424875695421236

In [19]:
entropy(np.array( [100,60,40]))

1.4854752972273344

In [20]:
#convert the documents that contain the word "associ" from dictionary keys to a list
associ_docs = list(dtm.get_token_occurences('associ').keys())
associ_docs

['Dentistry00500.txt',
 'Dentistry00502.txt',
 'Dentistry00503.txt',
 'Dentistry00505.txt',
 'Dentistry00506.txt',
 'Dentistry00512.txt',
 'Dentistry00514.txt',
 'Dentistry00515.txt',
 'Dentistry00516.txt',
 'Dentistry00518.txt',
 'Dentistry00521.txt',
 'Dentistry00523.txt',
 'Dentistry00524.txt',
 'Dentistry00525.txt',
 'Dentistry00526.txt',
 'Dentistry00528.txt',
 'Dentistry00529.txt',
 'Dentistry00530.txt',
 'Dentistry00533.txt',
 'Dentistry00534.txt',
 'Dentistry00535.txt',
 'Dentistry00536.txt',
 'Dentistry00537.txt',
 'Dentistry00538.txt',
 'Dentistry00541.txt',
 'Dentistry00542.txt',
 'Dentistry00544.txt',
 'Dentistry00548.txt',
 'Dentistry00549.txt',
 'Dentistry00550.txt',
 'Dentistry00552.txt',
 'Dentistry00553.txt',
 'Dentistry00554.txt',
 'Dentistry00555.txt',
 'Dentistry00556.txt',
 'Dentistry00557.txt',
 'Dentistry00558.txt',
 'Dentistry00559.txt',
 'Depression00500.txt',
 'Depression00501.txt',
 'Depression00505.txt',
 'Depression00506.txt',
 'Depression00509.txt',
 'Depr

In [21]:
#print the number of "Dentistry" documents that contain the word "associ"
sub = 'Dentistry'
count_dentistry = 0
for item in associ_docs:
    if sub in item:
        count_dentistry += 1
print(count_dentistry)

38


In [22]:
#print the number of "Depression" documents that contain the word "associ"
sub = 'Depression'
count_depression = 0
for item in associ_docs:
    if sub in item:
        count_depression += 1
print(count_depression)

22


In [23]:
#print the number of "Diabetes" documents that contain the word "associ"
sub = 'Diabetes'
count_diabetes = 0
for item in associ_docs:
    if sub in item:
        count_diabetes += 1
print(count_diabetes)

62


In [24]:
#this is an important step
#make an array, rows represent "Dentistry", "Depression", and "Diabetes" respectively. Columns represent the number of documents that contains the word "associ" and the number of documents that do NOT contain the word "associ"
array = np.reshape((count_dentistry,60-count_dentistry,count_depression,40-count_depression,count_diabetes,100-count_diabetes ),(3,2))

In [25]:
array

array([[38, 22],
       [22, 18],
       [62, 38]])

In [26]:
#calculate the column sum of the array
np.sum(array, axis = 0)

array([122,  78])

In [27]:
#calculate the entroy of the word "associ"
entropy(np.array( [122,78]))

0.9647995485050872

In [28]:
#calculate the entropy of the document class (Dentistry, Depression, and Diabetes)
entropy_class = entropy(np.array([60,40,100]))

In [29]:
entropy_class

1.4854752972273344

In [30]:
#calculate the column probabilities
column_probs = np.sum(array, axis = 0)/200

In [31]:
column_probs

array([0.61, 0.39])

In [32]:
#calculate the column entropies
column_entropy = np.apply_along_axis(entropy, 0, array)

In [33]:
column_entropy

array([1.46607412, 1.50864079])

In [34]:
#Two random variables: X (document class) and Y (associ's presense or absence). I (X;Y) = H(X) - H(X|Y)
column_probs*column_entropy

array([0.89430521, 0.58836991])

In [35]:
conditional_entropy = sum(column_probs*column_entropy)

In [36]:
conditional_entropy

1.4826751237111302

In [37]:
#calculate the mutual information between the word "associ" and the document class (Dentistry, Depression, and Diabetes)
# the approach above used entropy reduction for the mutual information instead of joint probability
MI_associ = entropy_class - conditional_entropy

In [38]:
MI_associ

0.0028001735162042074